sfs_visualizer::MatlabFieldViewer Class Reference
A FieldViewer for Matlab files.
#include <matlabfieldviewer.h>
Public Member Functions
virtual void update ()
methods
virtual void key (unsigned char key, int x, int y)
user inputs
virtual void mouse (int button, int state, int x, int y)
virtual void specialkey (int key, int x, int y)
virtual void timer (int updateRateMs)
Protected Member Functions
virtual void draw_impl ()
virtual void initProperties ()
Private Member Functions
void readMatlabfile (const char *file_name)
void updateTexture ()
void initTask (boost::exception_ptr &error)
the matlabfile is loaded from a background thread
Private Attributes
float _left
float _up
Shader * _shader
bool _bInitalLoad
bool _bCutMode
float _radiusScale
int _matlabfilesCount
Additional Inherited Members
Detailed Description
A FieldViewer for Matlab files.
Definition at line 29 of file matlabfieldviewer.h.
Member Function Documentation
void MatlabFieldViewer::update () [virtual]
methods
Reimplemented from sfs_visualizer::RenderObjectBase< FieldViewerBase > .
Definition at line 290 of file matlabfieldviewer.cpp.
void MatlabFieldViewer::key (unsigned char key, int x, int y) [virtual]
user inputs
Reimplemented from sfs_visualizer::FieldViewerBase .
Definition at line 166 of file matlabfieldviewer.cpp.
References sfs_visualizer::RenderObjectBase< FieldViewerBase >::IsVisible(), sfs_visualizer::RenderObjectBase< TYPE >::IsVisible(), and sfs_visualizer::FieldViewerBase::key().
void MatlabFieldViewer::initTask (boost::exception_ptr & error) [private]
the matlabfile is loaded from a background thread
Definition at line 19 of file matlabfieldviewer.cpp.
The documentation for this class was generated from the following files:
matlabfieldviewer.h
matlabfieldviewer.cpp