sfs_visualizer::FieldViewerBase Class Reference
A Base class for classes that can show soundfields either with shearwarping or a raytracer.
#include <fieldviewerbase.h>
Public Member Functions
virtual void key (unsigned char key, int x, int y)
user inputs
virtual void timer (int updateRateMs)
virtual const std::string Info () const
Informators and Mutators.
virtual void IsVisible (bool bVisible)
Protected Member Functions
virtual void draw_impl ()
virtual void newTexture (TextureFactory::TYPE type=TextureFactory::FLOAT)
virtual void initProperties ()
void addQuadslice (float zOffset)
void switchAlpha ()
void blend (int blend)
void toggleRenderMode ()
Toggle between Raytracer and Shearwarping.
void drawBorder ()
void initSSBO (GLuint index, bool bRand)
Initializes and creates a Shader Storage Buffer.
void fillSSBO (const GLvoid *buffer, GLsizeiptr size, GLuint index)
fill a Shader Storage Buffer with data
Protected Attributes
std::stringstream _info
std::vector< GLuint > _textures
float z
Shader * _fragmentShader
Shader * _vertexShader
int _currenttexture
int _alphablendfunction
int _alphablendmode
float _alphatest
int WIDTH
int HEIGHT
int DEPTH
int WORKGROUPSIZE
unsigned int _sources
bool _valueChanged
int _animationRunning
bool _bDrawBorder
CommandManager _cmdManager
float _sliceDist
Private Attributes
int _oldnSlizes
Additional Inherited Members
Detailed Description
A Base class for classes that can show soundfields either with shearwarping or a raytracer.
Definition at line 35 of file fieldviewerbase.h.
Member Function Documentation
void FieldViewerBase::key (unsigned char key, int x, int y) [virtual]
user inputs
Reimplemented from sfs_visualizer::RenderObjectBase< FieldViewerBase > .
Reimplemented in sfs_visualizer::ShaderSoundfieldViewerGreen , and sfs_visualizer::MatlabFieldViewer .
Definition at line 212 of file fieldviewerbase.cpp.
References toggleRenderMode().
Referenced by sfs_visualizer::MatlabFieldViewer::key().
const std::string FieldViewerBase::Info () const [virtual]
Informators and Mutators.
Implements sfs_visualizer::InfoProvider .
Definition at line 441 of file fieldviewerbase.cpp.
void FieldViewerBase::toggleRenderMode () [protected]
Toggle between Raytracer and Shearwarping.
Definition at line 173 of file fieldviewerbase.cpp.
Referenced by key().
void FieldViewerBase::initSSBO (GLuint index, bool bRand = false) [protected]
Initializes and creates a Shader Storage Buffer.
Definition at line 157 of file fieldviewerbase.cpp.
References fillSSBO(), and sfs_visualizer::RenderObjectBase< FieldViewerBase >::random().
void FieldViewerBase::fillSSBO (const GLvoid * buffer, GLsizeiptr size, GLuint index) [protected]
fill a Shader Storage Buffer with data
Definition at line 133 of file fieldviewerbase.cpp.
Referenced by initSSBO().
The documentation for this class was generated from the following files:
fieldviewerbase.h
fieldviewerbase.cpp